# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figurine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('movement', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('melee', models.SmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('range', models.SmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('strength', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('toughness', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('life', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('attacks', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor', models.SmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('invulnerability', models.SmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('points', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
