# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 12:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='command',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='figurine',
            name='picture',
            field=models.ImageField(null=True, upload_to='figurines'),
        ),
    ]
