# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0002_auto_20180424_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(height_field=512, null=True, upload_to='Faction', width_field=512)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='figurine',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurines', to='armory.Faction'),
        ),
        migrations.AddField(
            model_name='figurine',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurines', to='armory.Squad'),
        ),
    ]
