# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0005_auto_20180502_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigurineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='figurine',
            name='squad',
        ),
        migrations.AddField(
            model_name='figurinegroup',
            name='figurine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='armory.Figurine'),
        ),
        migrations.AddField(
            model_name='squad',
            name='figurine_group',
            field=models.ManyToManyField(to='armory.FigurineGroup'),
        ),
    ]
