# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0006_auto_20180502_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='figurine_group',
            new_name='figurines',
        ),
    ]
