# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0008_auto_20180502_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurine',
            name='faction',
        ),
        migrations.AddField(
            model_name='figurine',
            name='faction',
            field=models.ManyToManyField(null=True, related_name='figurines', to='armory.Faction'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='figurines',
            field=models.ManyToManyField(related_name='squads', to='armory.FigurineGroup'),
        ),
    ]
