# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0009_auto_20180502_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='faction',
            name='icon',
            field=models.ImageField(null=True, upload_to='faction'),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='faction',
            field=models.ManyToManyField(related_name='figurines', to='armory.Faction'),
        ),
        migrations.AlterField(
            model_name='role',
            name='icon',
            field=models.ImageField(null=True, upload_to='role'),
        ),
    ]
