# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 07:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(null=True, upload_to='faction')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('movement', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('melee', models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32)),
                ('range', models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32)),
                ('strength', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('toughness', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('life', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('attacks', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('command', models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('armor', models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32)),
                ('invulnerability', models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32)),
                ('points', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(null=True, upload_to='role')),
                ('display_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('power', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded_images')),
                ('army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurines', to='home.Army')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='home.Unit'),
        ),
        migrations.AddField(
            model_name='army',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Race'),
        ),
    ]
