# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attacks',
            field=models.CharField(choices=[(b'*', b'*'), (b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'D3', b'D3'), (b'2D3', b'2D3'), (b'3D3', b'3D3'), (b'D6', b'D6'), (b'2D6', b'2D6'), (b'3D6', b'3D6')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='command',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19'), (b'20', b'20'), (b'21', b'21'), (b'22', b'22'), (b'23', b'23'), (b'24', b'24'), (b'25', b'25'), (b'26', b'26'), (b'27', b'27'), (b'28', b'28'), (b'29', b'29'), (b'30', b'30')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melee',
            field=models.CharField(choices=[(b'*', b'*'), (b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movement',
            field=models.CharField(choices=[(b'*', b'*'), (b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='range',
            field=models.CharField(choices=[(b'*', b'*'), (b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strength',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='toughness',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12')], default=b'0', max_length=32),
        ),
    ]
