# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_figurine_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurine',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
