# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-30 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180824_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degressive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_profiles', to='home.DegressiveProfile'),
        ),
    ]
