# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180803_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
