# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_photo'),
    ]

    operations = [

    ]
