# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-03 16:25
from __future__ import unicode_literals

import awesome_avatar.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', awesome_avatar.fields.AvatarField(default=None, null=True, upload_to='avatars')),
            ],
        ),
        migrations.AddField(
            model_name='figurine',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(default=None, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
