# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-05 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_figurine_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurine',
            name='cropping',
        ),
    ]
