# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_figurine_cropping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faction',
            old_name='sub_faction',
            new_name='parent_faction',
        ),
    ]
