# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180806_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(null=True, upload_to='faction')),
            ],
        ),
        migrations.RemoveField(
            model_name='faction',
            name='parent_faction',
        ),
        migrations.AlterField(
            model_name='figurine',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurines', to='home.Army'),
        ),
        migrations.DeleteModel(
            name='Faction',
        ),
    ]
