# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180806_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='race',
            field=models.CharField(choices=[(b'OTHER', b'OTHER'), (b'IMPERIUM', b'IMPERIUM'), (b'CHAOS', b'CHAOS'), (b'XENOS', b'XENOS')], default=b'OTHER', max_length=32),
        ),
    ]
