# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_army_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Role'),
        ),
    ]
