# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-06 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_figurine_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-display_order']},
        ),
    ]
