# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180806_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('power', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurines', to='home.Army')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='figurinegroup',
            name='figurine',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='figurines',
        ),
        migrations.RemoveField(
            model_name='figurine',
            name='army',
        ),
        migrations.RemoveField(
            model_name='figurine',
            name='role',
        ),
        migrations.DeleteModel(
            name='FigurineGroup',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.AddField(
            model_name='figurine',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Unit'),
        ),
    ]
