# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180807_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurine',
            name='picture',
        ),
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
