# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180807_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Figurine',
            new_name='Profile',
        ),
    ]
