# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180810_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='armor',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invulnerability',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melee',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='range',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'1+'), (b'2', b'2+'), (b'3', b'3+'), (b'4', b'4+'), (b'5', b'5+'), (b'6', b'6+')], default=b'0', max_length=32),
        ),
    ]
